In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

# 生成样本数据， 特征维度为2
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3

# 先使用sklearn自带的库来解决
model = LinearRegression().fit(X, y)

# 打印参数以及偏移量（bias）
print ("基于sklearn的线性回归模型参数为 coef: ", model.coef_, " intercept: %.5f" %model.intercept_)

# TODO: 动手实现多元线性回归的参数估计, 把最后的结果放在res变量里。 res[0]存储的是偏移量，res[1:]存储的是模型参数

# 手动实现参数的求解。先把偏移量加到X里
a = np.ones(X.shape[0]).reshape(-1,1)
X = np.concatenate((a, X), axis=1)

# res = np.matmul(np.linalg.inv(np.matmul(X.T,X)),np.matmul(X.T,y))
res = np.matmul(np.linalg.inv(np.matmul(X.T, X)),  np.matmul(X.T, y))

# 打印参数以偏移量（bias）
print ("通过手动实现的线性回归模型参数为 coef: ", res[1:], " intercept: %.5f"%res[0])

基于sklearn的线性回归模型参数为 coef:  [1. 2.]  intercept: 3.00000
通过手动实现的线性回归模型参数为 coef:  [1. 2.]  intercept: 3.00000


In [2]:
res[1:]

array([1., 2.])

In [3]:
res[0]

3.0

In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
# 生成样本数据， 特征维度为2
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3

In [6]:
# 先使用sklearn自带的库来解决
model = LinearRegression().fit(X, y)

In [7]:
# 打印参数以及偏移量（bias）
print ("基于sklearn的线性回归模型参数为 coef: ", model.coef_, " intercept: %.5f" %model.intercept_)

基于sklearn的线性回归模型参数为 coef:  [1. 2.]  intercept: 3.00000


In [8]:

a = np.ones(X.shape[0])

In [9]:
a

array([1., 1., 1., 1.])

In [10]:
a = np.ones(X.shape[0]).reshape(-1,1)

In [11]:
a

array([[1.],
       [1.],
       [1.],
       [1.]])

In [12]:
np.eye(X.shape[0])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [14]:
X = np.concatenate((a, X), axis=1)

In [15]:
X

array([[1., 1., 1.],
       [1., 1., 2.],
       [1., 2., 2.],
       [1., 2., 3.]])

In [16]:
y

array([ 6,  8,  9, 11])

In [17]:
XMat = np.mat(X)
yMat = np.mat(y)

In [18]:
XMat

matrix([[1., 1., 1.],
        [1., 1., 2.],
        [1., 2., 2.],
        [1., 2., 3.]])

In [19]:
yMat

matrix([[ 6,  8,  9, 11]])

In [20]:
XMat.shape

(4, 3)

In [21]:
(XMat.T*XMat).shape

(3, 3)

In [22]:
(XMat.T*XMat).I.shape

(3, 3)

In [23]:
res = ((XMat.T*XMat).I)*(XMat.T*yMat.T)

In [24]:
res

matrix([[3.],
        [1.],
        [2.]])

In [25]:
res[1:]

matrix([[1.],
        [2.]])

In [26]:
res[0]

matrix([[3.]])

In [27]:
res[1:].A

array([[1.],
       [2.]])

In [28]:
res[1:].A.T

array([[1., 2.]])

In [29]:
res[0].A

array([[3.]])

In [30]:
res[1:].A.flatten()

array([1., 2.])

In [33]:
res[0].A.flatten()

array([3.])

In [36]:
print ("通过手动实现的线性回归模型参数为 coef: ", res[1:].A.flatten(), " intercept: %.5f"%res[0])

通过手动实现的线性回归模型参数为 coef:  [1. 2.]  intercept: 3.00000
